# Generated by Django 5.0 on 2023-12-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='variant',
            new_name='variant_id',
        ),
    ]
