# Generated by Django 5.0 on 2023-12-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0002_rename_product_productvariant_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='variant_id',
            new_name='variant',
        ),
    ]
