data = [
    {
        "id": 1,
        "name": "PARA LOS QUE VAN INICIANDO",
        "specific_name": "KIT DE PESAS 16 DISCOS 34KG EN TOTAL, BARRA Z, BARRA RECTA Y MANCUERNAS | ENVÍO GRATIS",
        "price": 1600,
        "weight": 34,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "product_group": 1,
        "name_product_group": "34KG con 16 Discos",
        "express_payment_link": "https://buy.stripe.com/3cs4hn6FufSb7wAbKJ",
        "cost": 0
    },
    {
        "id": 3,
        "name": "PARA LOS QUE VAN RÁPIDO",
        "specific_name": "SOPORTE DE INMERSIÓN PARA ENTRENAMIENTO FÍSICO, BARRA DE INMERSIÓN | ENVÍO GRATIS",
        "price": 1599,
        "weight": 10,
        "top_seller": True,
        "category": 2,
        "express_payment_link": "https://buy.stripe.com/14kaFLaVK21l3gk8yG",
        "cost": 0,
        "primary": True
    },
    {
        "id": 4,
        "name": "PARA QUIEN QUIERE TODO, SIN ESPACIO",
        "specific_name": "KIT 16 DISCOS 42KG EN TOTAL MANCUERNAS, BARRA RECTA, BARRA Z BARRA ROMANA | ENVÍO GRATIS",
        "price": 2100,
        "weight": 42,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "product_group": 2,
        "name_product_group": "42KG con 16 Discos",
        "express_payment_link": "https://buy.stripe.com/6oE9BH7JyfSbcQU2aj",
        "cost": 0
    },
    {
        "id": 5,
        "name": "PARA LOS QUE YA NO VAN AL GYM",
        "specific_name": "KIT 80KG MANCUERNAS, BARRA ROMANA, BARRA Z, BARRA RECTA | ENVÍO GRATIS",
        "price": 3700,
        "weight": 80,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "product_group": 2,
        "name_product_group": "80KG con 28 Discos",
        "express_payment_link": "https://buy.stripe.com/6oEdRX5BqbBV0484is",
        "cost": 0
    },
    {
        "id": 6,
        "name": "PARA LOS QUE SOLO OCUPAN MANCUERNAS",
        "specific_name": "PAR DE MANCUERNAS DE ACERO CON 10KG CADA UNA PESO TOTAL 20KG",
        "price": 1450,
        "weight": 20,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "express_payment_link": "https://buy.stripe.com/dR629f8NC35pcQU9CN",
        "cost": 0
    },
    {
        "id": 7,
        "name": "PARA LOS QUE HACEN CALISTENIA",
        "specific_name": "BARRAS 8 EN 1 SUPER REFORZADAS ENVÍO GRATIS",
        "price": 1600,
        "top_seller": True,
        "category": 2,
        "express_payment_link": "https://buy.stripe.com/28o15b7JyfSbaIMeX8",
        "cost": 0
    },
    {
        "id": 8,
        "name": "PARA QUIEN QUIERE LO NECESARIO, SIN ESPACIO",
        "specific_name": "KIT DE PESAS CON 52KG DISCOS DE ACERO PARA PASAR AL SIGUIENTE NIVEL | ENVÍO GRATIS",
        "price": 3800,
        "weight": 52,
        "top_seller": True,
        "category": 1,
        "express_payment_link": "https://buy.stripe.com/5kA3dj4xm9tNdUY8yL",
        "cost": 0
    },
    {
        "id": 9,
        "name": "PARA LOS QUE VAN INICIANDO 42kg",
        "specific_name": "KIT DE PESAS 16 DISCOS 42KG EN TOTAL, BARRA Z, BARRA RECTA Y MANCUERNAS | ENVÍO GRATIS",
        "price": 1850,
        "weight": 42,
        "count_discs": True,
        "top_seller": False,
        "category": 1,
        "product_group": 1,
        "name_product_group": "42KG con 16 Discos",
        "express_payment_link": "https://buy.stripe.com/cN2aFL8NC0Xhg368yV",
        "cost": 0
    },
    {
        "id": 10,
        "name": "PARA LOS QUE VAN INICIANDO 50kg",
        "specific_name": "KIT DE PESAS 20 DISCOS 50KG EN TOTAL, BARRA Z, BARRA RECTA Y MANCUERNAS | ENVÍO GRATIS",
        "price": 2100,
        "weight": 50,
        "count_discs": True,
        "top_seller": False,
        "category": 1,
        "product_group": 1,
        "name_product_group": "50KG con 20 Discos",
        "express_payment_link": "https://buy.stripe.com/6oE7tzd3SgWf4ko6qF",
        "cost": 0
    },
    {
        "id": 11,
        "name": "PARA LOS QUE DISFRUTAN DE INTERCAMBIAR PESOS",
        "specific_name": "KIT DE 2 SEGUROS PARA BARRAS Y MANCUERNAS STANDARD DE UNA PULGADA, DE METAL, PARA EL INTERCAMBIO RÁPIDO Y PRÁCTICO DE DISCOS | ENVÍO GRATIS",
        "price": 169,
        "weight": 0.5,
        "count_discs": False,
        "top_seller": False,
        "category": 3,
        "express_payment_link": "https://buy.stripe.com/8wMbJP9RGcFZ0487uo",
        "cost": 0
    },
    {
        "id": 12,
        "name": "PARA LOS QUE QUIEREN HACER REMO CON PESAS",
        "specific_name": "BARRA ROMANA ESTÁNDAR DE UNA PULGADA 15KG ACERO BLACK | ENVÍO GRATIS",
        "price": 899,
        "weight": 15,
        "count_discs": False,
        "top_seller": False,
        "category": 3,
        "express_payment_link": "https://buy.stripe.com/fZeaFL8NC6hB3gkcP4",
        "cost": 0
    },
    {
        "id": 13,
        "name": "PARA LOS QUE QUIEREN HACER EL PREDICADOR EN CASA",
        "specific_name": "BARRA Z SOLIDA DE ACERO CON SEGUROS, 12KG EN TOTAL SOPORTA 350KG PARA DISCOS DE UNA PULGADA ESTÁNDAR | ENVÍO GRATIS",
        "price": 999,
        "weight": 12,
        "count_discs": False,
        "top_seller": False,
        "category": 3,
        "express_payment_link": "https://buy.stripe.com/eVabJP5BqdK39EIeXd",
        "cost": 0
    },
    {
        "id": 14,
        "name": "PARA LOS QUE QUIEREN HACER EL PREDICADOR EN CASA SIN EXCEDERSE",
        "specific_name": "BARRA Z CON 2 SEGUROS PARA DISCOS STANDARD DE UNA PULGADA, SOPORTA 60KG | ENVÍO GRATIS",
        "price": 499,
        "weight": 1,
        "count_discs": False,
        "top_seller": False,
        "category": 3,
        "express_payment_link": "https://buy.stripe.com/aEU15b1la5dx9EIcP6",
        "primary": True,
        "cost": 150,
        "cost": 0
    },
    {
        "id": 15,
        "name": "PARA LOS QUE QUIEREN HACER REMO CON PESAS SIN EXCEDERSE",
        "specific_name": "BARRA ROMANA CON 2 SEGUROS PARA DISCOS STANDARD DE UNA PULGADA, SOPORTA 60KG | ENVÍO GRATIS",
        "price": 499,
        "weight": 1,
        "count_discs": False,
        "top_seller": False,
        "category": 3,
        "express_payment_link": "https://buy.stripe.com/14kg05aVKgWf2cg3ex",
        "primary": True,
        "cost": 250,
    },
    {
        "id": 16,
        "name": "PARA LOS QUE SOLO OCUPAN MANCUERNAS",
        "specific_name": "PAR DE MANCUERNAS DE 10KG EN TOTAL 20 KG SON 2 PIEZAS | ENVÍO GRATIS",
        "price": 1100,
        "weight": 20,
        "count_discs": True,
        "top_seller": False,
        "category": 1,
        "product_group": 3,
        "name_product_group": "10Kg C/U total 20kg",
        "express_payment_link": "https://buy.stripe.com/3cs15b1la49t9EI02m",
        "primary": True,
        "cost": 450
    },
    {
        "id": 17,
        "name": "PARA LOS QUE OCUPAN MANCUERNAS y BARRA",
        "specific_name": "BARRA 22KG + PAR MANCUERNAS 10KG EN TOTAL 42KG A DOMICILIO PAGAS A TU ENTREGA 16 DISCOS | ENVÍO GRATIS",
        "price": 1580,
        "weight": 42,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "express_payment_link": "https://buy.stripe.com/6oE7tz4xmaxR0483cd",
        "cost": 0
    },
    {
        "id": 18,
        "name": "PARA LOS QUE SOLO OCUPAN MANCUERNAS",
        "specific_name": "PAR DE MANCUERNAS DE 6KG EN TOTAL 12 KG SON 2 PIEZAS | ENVÍO GRATIS",
        "price": 790,
        "weight": 12,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "product_group": 3,
        "name_product_group": "6Kg C/U total 12kg",
        "express_payment_link": "https://buy.stripe.com/00g8xD3tieO7bMQ5mA",
        "primary": True,
        "cost": 300
    },
    {
        "id": 19,
        "name": "PARA LOS QUE SOLO OCUPAN MANCUERNAS",
        "specific_name": "PAR DE MANCUERNAS DE 8KG EN TOTAL 16 KG SON 2 PIEZAS | ENVÍO GRATIS",
        "price": 799,
        "weight": 16,
        "count_discs": True,
        "top_seller": False,
        "category": 1,
        "product_group": 3,
        "name_product_group": "8Kg C/U total 16kg",
        "express_payment_link": "https://buy.stripe.com/fZe4hn1ladK33gk02n",
        "cost": 0
    },
    {
        "id": 20,
        "name": "PARA LOS QUE SOLO OCUPAN MANCUERNAS",
        "specific_name": "PAR DE MANCUERNAS DE 4KG EN TOTAL 8 KG SON 2 PIEZAS | ENVÍO GRATIS",
        "price": 530,
        "weight": 8,
        "count_discs": True,
        "top_seller": False,
        "category": 1,
        "product_group": 3,
        "name_product_group": "4Kg C/U total 8kg",
        "express_payment_link": "https://buy.stripe.com/7sI3dj0h67lF5osbL6",
        "cost": 0
    },
    {
        "id": 21,
        "name": "PARA LOS QUE SOLO OCUPAN BARRA",
        "specific_name": "BARRA RECTA DE 22KG 8 DISCOS AJUSTABLES, PESOS VARIABLES | ENVÍO GRATIS",
        "price": 1000,
        "weight": 22,
        "count_discs": True,
        "top_seller": True,
        "category": 1,
        "name_product_group": "22Kg con 8 Discos",
        "express_payment_link": "https://buy.stripe.com/7sI3dj0h67lF5osbL6",
        "cost": 430,
        "primary": True
    },
]