# Generated by Django 4.2.7 on 2023-11-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='we_mean',
            field=models.TextField(default=None, null=True),
        ),
    ]
