# Generated by Django 5.0 on 2023-12-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
    ]
