# Generated by Django 5.0 on 2023-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_discs',
            field=models.BooleanField(default=False),
        ),
    ]
