# Generated by Django 4.2.7 on 2024-01-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0002_productvariant_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='material',
        ),
    ]
