data = [            
    {"id":1,"name": 'Blusas'},            
    {"id":2,"name": 'Camisetas'},             
    {"id":3,"name": 'Suéteres'},
    {"id":4,"name": 'Camisas'},
    {"id":5,"name": 'Camisetas'},                                                        
    {"id":6,"name": 'Pantalones'},
    {"id":7,"name": 'Jeans'},
    {"id":8,"name": 'Faldas'},
    {"id":9,"name": 'Shorts'},
    {"id":10,"name": 'Vestidos'},
    {"id":11,"name": 'Accesorios'},
    {"id":12,"name": 'Calzado'},
    {"id":13,"name": 'Bolsos y Mochilas'},
    {"id":14,"name": 'Niñas'},
    {"id":15,"name": 'Niños'},
    {"id":16,"name": 'Bebés'},
]
