# Generated by Django 4.2.7 on 2024-01-31 00:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
