# Generated by Django 4.2.7 on 2024-01-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
