version: '3'

services:
  microservice_enid:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SERVICENAME}_service
    container_name: ${SERVICENAME}_service
    ports:
      - "8085:8080"
      - "5678:5678"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    networks:
      - backend
      - enid_service_network

  redis:
    container_name: ${SERVICENAME}_redis 
    image: redis:alpine
    command: sh -c "rm -rf /data/* && redis-server"
    volumes:
      - redis_data:/data
    networks:
      - backend

  postgres:
    container_name: ${SERVICENAME}_postgres
    image: postgres:alpine
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
   
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      
  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust/test
    command: ["locust", "-f", "/mnt/locust/test/locustfile.py", "--host", "http://app:8085"]
    depends_on:
      - microservice_enid
    networks:
      - backend

volumes:
  redis_data:
  postgres_data:


networks:
  backend:
    driver: bridge
  enid_service_network:
    external: true