version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: enid_service:0.1
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vuejs

  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: enid_service_vue:0.1
    ports:
      - "5173:5173"  
    env_file:
      - .env
  
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: