version: '3'

services:
  microservice_enid:
    build:
      context: .
      dockerfile: Dockerfile
    image: enidservice_service
    ports:
      - "8000:8000"
    env_file:
      - .env

    depends_on:
      - redis
      - postgres
    networks:
      - backend

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
   
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  redis_data:
  postgres_data:

networks:
  backend:
    driver: bridge
