# Generated by Django 5.0 on 2023-12-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=255)),
                ('short_answer', models.TextField(default=None, null=True)),
                ('path_seccion', models.CharField(max_length=255, null=True)),
                ('call_to_action', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
