# Generated by Django 4.2.7 on 2023-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='path_seccion',
            field=models.URLField(default=None, null=True),
        ),
    ]
