# Generated by Django 4.2.7 on 2023-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returns_path_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='answer',
            field=models.TextField(),
        ),
    ]
