# Generated by Django 4.2.7 on 2023-12-02 22:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_alter_returns_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
