# Generated by Django 4.2.7 on 2023-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_alter_returns_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='answer',
        ),
        migrations.AddField(
            model_name='returns',
            name='short_answer',
            field=models.TextField(default=None, null=True),
        ),
    ]
