# Generated by Django 4.2.7 on 2023-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_remove_returns_answer_returns_short_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='time_condition',
            field=models.TextField(default=None, null=True),
        ),
    ]
