# Generated by Django 4.2.7 on 2023-12-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_returns_time_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='time_condition',
        ),
        migrations.AddField(
            model_name='returns',
            name='call_to_action',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
