# Generated by Django 4.2.7 on 2023-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0007_remove_returns_time_condition_returns_call_to_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='path_seccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
