export const fields = {   
    form: {
        email: "",
        name: "",
        postal_code: "",
        street: "",
        number: "",
        interior_number: "",
        colony: "",
        delegation_or_municipality: "",
        city: "",
        state: "",
        additional_details: "",
        phone_number: "",
        products: [],
        stripe_token: "",        
    },
    errors: {
        state:"",
        email: "",
        name: "",
        postal_code: "",
        street: "",
        number: "",
        interior_number: "",
        colony: "",
        delegation_or_municipality: "",
        city: "",
        additional_details: "",
        phone_number: "",
        stripe_error: "",
    },
    stateHelper: null,
    paymentHelper: null,    
    cart: null,
    user: null,
    sendUserLead: false,
    loading: false,
    stripe_message_error: "",
    states: [],
}