# Generated by Django 4.2.7 on 2023-12-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('long', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disc', models.BooleanField(default=False)),
            ],
        ),
    ]
