# Generated by Django 5.0 on 2023-12-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
    ]
