# Generated by Django 5.0 on 2023-12-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_variants'),
        ('variants', '0003_remove_variant_pieces_remove_variant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='products',
            field=models.ManyToManyField(related_name='variant_products', to='products.product'),
        ),
    ]
