# Generated by Django 5.0 on 2023-12-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0004_variant_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='products',
        ),
    ]
