# Generated by Django 5.0 on 2023-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0005_remove_variant_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='weight_multipliable',
            field=models.BooleanField(default=True),
        ),
    ]
