# Generated by Django 5.0 on 2023-12-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0006_variant_weight_multipliable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='weight_multipliable',
        ),
    ]
