# Generated by Django 5.0 on 2023-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0007_remove_variant_weight_multipliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='disc',
            field=models.BooleanField(default=False),
        ),
    ]
