name: Vue.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci
      working-directory: enid-store/enid/frontend

    - name: Build application
      run: npm run build
      working-directory: enid-store/enid/frontend

    - name: Run tests
      run: npm run test
      working-directory: enid-store/enid/frontend
